stages:
- deploy

deploy:
  stage: deploy
  image:
    name: node:8-alpine
    entrypoint: ["ash", "-c"]
  script:
  - npm install -g firebase-tools
  - firebase target:apply -P ${GCP_PROJECT_ID} hosting home ${FIREBASE_HOSTING_SITE}
  - firebase deploy -P ${GCP_PROJECT_ID}
  environment:
    name: production
  only:
  - tags

